### ISSUE TITLE
Too much access

### ISSUE THREAD

**Issue by fulldecent** [developmentseed/jekyll-hook#29]
This is a server, which requires too much access. I am hoping for a script which can live on normal commodity cPanel servers and do the same thing.

**Comment by scisco** [comment]
@fulldecent I'm not sure if jekyll-hook requires root access if it is probably configured.

**Comment by fulldecent** [comment]
Sorry for the lack of clarity. My issue is that this program requires the following to run: 

 * git
 * npm
 * nodejs
 * shell access
 * ruby
 * Permission to symlink in `/usr/bin/node`
 * ability to run long-running servers
 * nginx

I would like to run this program on my server which only provides the first three. Before I go and write my own script which does the same thing, I was hoping that `jekyll-hook` could be set up as a normal script that I run on the server which will allow it git pull and jekill build.

**Comment by fulldecent** [comment]
Closing, project no longer maintained. Not critical to fix.
